import Head from 'next/head'
import styles from '../styles/addOper.module.css'
import { useRouter } from 'next/dist/client/router'
import React from 'react'
import AddOperatorForm from '../components/addOperatorForm'

const AddOper = () => {
    const router = useRouter();

    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>New Operator</title>
                    <meta name="description" content="Generated by create next app" />
                </Head>
                <main className={styles.main}>
                    <h1>
                        <input type='image' className={styles.backButton} src='http://cdn.onlinewebfonts.com/svg/img_490217.png' alt="backButton" onClick={() => router.push("/")}/>
                        Добавить оператора
                    </h1>
                    <AddOperatorForm />
                </main>
            </div>
        </>
    )
}

export default AddOper