import Head from 'next/head'
import styles from '../styles/Home.module.css'
import beeline from '../images/Beeline.png'
import megafon from '../images/megafon.png'
import mtc from '../images/MTC.jpg'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Пополнение баланса
        </h1>
        
        <div className={styles.grid}>
          <Link href={'/payment'}><a className={styles.card}>
            <h2>МТС</h2>
          </a></Link>

          <Link href={'/payment'}><a className={styles.card}>
            <h2>Билайн</h2>
          </a></Link>

          <Link href={'/payment'}><a className={styles.card}  >
            <h2>Мегафон</h2>
          </a></Link>
        </div>
      </main>
    </div>
  )
}
