import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Beeline from 'images\Beeline.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Пополнение баланса
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>МТС &rarr;</h2>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Билайн&rarr;</h2>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}  >
            <h2>Мегафон &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  )
}
