/* eslint-disable @next/next/no-img-element */
import Head from "next/head"
import React from "react"
import { IOperator } from "../../types/operator"
import styles from '../../styles/payment.module.css'
import { NextPageContext } from 'next'
import { useRouter } from "next/dist/client/router"
import PaymentForm from "../../components/paymentForm"

interface ISomeInter {
    operator: IOperator
}

const Operator = ({ operator }: ISomeInter) => {
    const router = useRouter();

    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>{operator.name}</title>
                    <meta name="description" content="Generated by create next app" />
                </Head>
                <main className={styles.main}>
                    <h1>
                        <input type='image' className={styles.backButton} src='http://cdn.onlinewebfonts.com/svg/img_490217.png' alt="backButton" onClick={() => router.push("/")}></input>
                        Пополнение баланса {operator.name}
                    </h1>
                    <PaymentForm />
                </main>
            </div>
        </>
    )
}

export default Operator

Operator.getInitialProps = async ({ query }: NextPageContext) => {
    const response = await fetch(`https://bravedevelopers-operators.herokuapp.com/operators/${query.id}`);
    const operator: IOperator = await response.json();
    return { operator }
}

